backend:
  # If you want to test changes made to your config.yml file locally: 
  # Swap out "github" with "test-repo" and 
  # Navigate to localhost:3333/static/admin/index.html to view Netlify CMS locally. 
  name: github
  repo: texas-justice-initiative/website-nextjs
  branch: master
  # This line should *not* be indented
media_folder: static/images/uploads
publish_mode: editorial_workflow
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Newsfeed"
      name: "news"
      file: "content/newsfeed.md"
      fields:
        - {label: "Heading", name: "heading", widget: "string"}
        - {label: "Intro", name: "intro", widget: "markdown"}
        - label: "News"
          name: "news"
          widget: "list"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
            - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
            - {label: "Article Link", name: "link", widget: "string", pattern: ['^https?:\/\/.+\..+', 'Must be a URL']}
            - {label: "Description", name: "description", widget: "markdown"}
    - label: "Publications"
      name: "publications"
      file: "content/publications.md"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: "Newsletter sidebar heading", name: "newslettersHeading", widget: "string"}
        - {label: "Newsletter sidebar intro", name: "newslettersIntro", widget: "text"}
        - label: "Newsletters"
          name: "newsletters"
          widget: "list"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "URL", name: "url", widget: "string", pattern: ['^https?:\/\/.+\..+', 'Must be a URL']}
    - label: "About Us"
      name: "aboutUs"
      file: "content/about-us.md"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Mission", name: "mission", widget: "text"}
        - {label: "Body", name: "body", widget: "markdown"}
        - label: "Who we are"
          name: "who"
          widget: "object"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - label: "Executive Director"
              name: "executiveDirector"
              widget: "object"
              fields:
                - {label: "Name", name: "name", widget: "string"}
                - {label: "Biography", name: "biography", widget: "markdown"}
                - {label: "Headshot", name: "headshot", widget: "image"}
            - label: "Volunteer team"
              name: "volunteerTeam"
              widget: "object"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - label: "Volunteers"
                  name: "volunteers"
                  widget: "list"
                  fields:
                    - {label: "Name", name: "name", widget: "string"}
                    - {label: "Title", name: "title", widget: "string"}
                    - {label: "Headshot", name: "headshot", widget: "image"}
            - label: "Governance"
              name: "governance"
              widget: "object"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Body", name: "body", widget: "markdown"}
                - label: "Board members"
                  widget: "list"
                  name: "boardMembers"
                  fields:
                    - {label: "Name", name: "name", widget: "string"}
                    - {label: "Biography", name: "biography", widget: "markdown"}
                    - {label: "Headshot", name: "headshot", widget: "image"}
            - label: "Donors"
              name: "donors"
              widget: "object"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Body", name: "body", widget: "markdown"}
                - label: "Donor logos"
                  widget: "list"
                  name: "donorLogos"
                  fields:
                    - {label: "Name", name: "name", widget: "string"}
                    - {label: "Logo", name: "logo", widget: "image"}
  - name: "components"
    label: "Components"
    files:
    - label: "About sidebar"
      name: "aboutSidebar"
      file: "content/about-sidebar.md"
      fields:
        - {label: "Body", name: "body", widget: "markdown"}
media_library:
  name: "cloudinary"
  config:
    cloud_name: "texas-justice-initiative"
    api_key: "117183127965674"
