name: ESLint

on: [push, pull_request]

jobs:
  build:
    if: ${{ !startsWith(github.head_ref, 'cms/') }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.13.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.13.0
    - name: npm run lint
      run: |
        npm install
        npm run lint
      env:
        CI: true
